# Generated by Django 4.1 on 2022-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50, verbose_name='Servicio')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('texto', models.CharField(max_length=50, verbose_name='Texto')),
                ('image', models.ImageField(upload_to='veterinaria/images/')),
            ],
        ),
    ]
